const { ROLES } = require("./roles");

const PERMISSIONS = Object.freeze({
  VIEW_APP: "VIEW_APP",
  USE_AI: "USE_AI",
  MANAGE_USERS: "MANAGE_USERS",
  MANAGE_ROLES: "MANAGE_ROLES",
  MANAGE_PLANS: "MANAGE_PLANS",
  MANAGE_PAYMENTS: "MANAGE_PAYMENTS",
  VIEW_METRICS: "VIEW_METRICS",
  VIEW_AUDIT_LOGS: "VIEW_AUDIT_LOGS",
  MANAGE_SETTINGS: "MANAGE_SETTINGS",
  MANAGE_SYSTEM: "MANAGE_SYSTEM"
});

const ROLE_PERMISSIONS = Object.freeze({
  [ROLES.ADMIN_MASTER]: Object.values(PERMISSIONS),

  [ROLES.ADMIN]: [
    PERMISSIONS.VIEW_APP,
    PERMISSIONS.USE_AI,
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.MANAGE_ROLES,
    PERMISSIONS.MANAGE_PLANS,
    PERMISSIONS.MANAGE_PAYMENTS,
    PERMISSIONS.VIEW_METRICS,
    PERMISSIONS.VIEW_AUDIT_LOGS,
    PERMISSIONS.MANAGE_SETTINGS
  ],

  [ROLES.OPERATOR]: [
    PERMISSIONS.VIEW_APP,
    PERMISSIONS.USE_AI,
    PERMISSIONS.VIEW_METRICS
  ],

  [ROLES.SUPPORT]: [
    PERMISSIONS.VIEW_APP,
    PERMISSIONS.USE_AI
  ],

  [ROLES.USER]: [
    PERMISSIONS.VIEW_APP,
    PERMISSIONS.USE_AI
  ]
});

function hasPermission(role, permission) {
  const permissions = ROLE_PERMISSIONS[role] || [];
  return permissions.includes(permission);
}

module.exports = {
  PERMISSIONS,
  ROLE_PERMISSIONS,
  hasPermission
};
